### ISSUE TITLE
[Feature]: 翻译 docs/faq.md

### ISSUE THREAD

**Issue by ruanye** [react-document/reactrouter#10]
### What is the new or updated feature that you are suggesting?

增加中文版

### Why should this feature be included?

增加中文版

**Comment by suruirui** [comment]
我翻译docs/faq.md，时间2021.12.28-2021.01.04

**Comment by ShirleyZmj** [comment]
我翻译docs/faq.md，时间2021.01.04-2021.01.11

**Comment by ShirleyZmj** [comment]
我翻译完了，提了pr
