### ISSUE TITLE
[Feature]: 书写中文版 README.MD 

### ISSUE THREAD

**Issue by ruanye** [react-document/reactrouter#12]
### What is the new or updated feature that you are suggesting?

书写中文版 README.MD

### Why should this feature be included?

书写中文版 README.MD

**Comment by Terence-Cheng** [comment]
我翻译 Readme.md，时间2021.12.29-2021.12.31

**Comment by ruanye** [comment]
> 我翻译 Readme.md，时间2021.12.29-2021.12.31
这个不是翻译，是写我么自己的 Readme.md 具体可以参考下别的翻译的 README.md
